<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="romilskr3" failures="1" tests="1" name="locked_out_login Tests" time="4.694" errors="0" timestamp="2023-02-08T02:49:19 GMT">
  <testcase classname="SwagLabsE2E.LoginPageTest" name="locked_out_login" time="4.136">
    <failure type="java.lang.AssertionError" message="expected [Epic sadface: Sorry, this user has been locked out] but found [Epic sadface: Sorry, this user has been locked out.]">
      <![CDATA[java.lang.AssertionError: expected [Epic sadface: Sorry, this user has been locked out] but found [Epic sadface: Sorry, this user has been locked out.]
at SwagLabsE2E.LoginPageTest.locked_out_login(LoginPageTest.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- locked_out_login -->
  <testcase classname="SwagLabsE2E.LoginPageTest" name="standard_user_login" time="0.0">
    <ignored/>
  </testcase> <!-- standard_user_login -->
</testsuite> <!-- locked_out_login Tests -->
